### ISSUE TITLE
X-coordinate overflow on the missions page

### ISSUE THREAD

**Issue by deyemiobaa** [zhadier/space-travelers#43]
Hi Team, you have done a really great job on this project and I must commend you for that.

I noticed a very tiny issue on your missions page. The page scrolls from left to right on mobile devices.
While this might seem like a nit-pick. It would be great to take care of it.

Cheers and best of luck 👍🏾

**Comment by andres-condezo** [comment]
Hi @deyemiobaa :wave: 
Paying attention to these small details and fixing them I think can make a big difference in the final product. Thank you for helping us improve our application by discovering this bug :+1: .

**Comment by zhadier** [comment]
Hey @deyemiobaa , like @andres-condezo said your input is truly appreciated. Thank you
